import AskChat from "@/components/AskChat";

export const metadata = {
  title: "Ask Krishna · The Gita Companion",
};

export default function AskPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 md:px-8 pt-4 md:pt-6 h-[calc(100dvh-72px)] md:h-[calc(100dvh-80px)] flex flex-col">
      <header className="mb-3 flex-shrink-0">
        <p className="text-[10px] uppercase tracking-[0.18em] text-dust-200/70">Ask</p>
        <h1 className="text-xl md:text-2xl font-serif-d text-dharma-400 mt-1 leading-tight">
          A conversation with Krishna
        </h1>
        <p className="text-[11px] md:text-[12px] text-dust-200/70 mt-1 leading-snug max-w-xl hidden md:block">
          Bring a real question. Pick a voice. The answer is generated by an LLM grounded in the
          18 chapters and concepts of this app - not the verbatim text. It is a paraphrase, not the source.
        </p>
      </header>

      <div className="flex-1 min-h-0">
        <AskChat />
      </div>
    </div>
  );
}
